version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    restart: always
  backend:
    # usar la carpeta de backend
    build: ./backend
    # conectarse con el puerto 3000 interno y 3000 para exponer al host
    ports:
      - '3000:3000'
    volumes:
    # vincular la carpeta del backend
      - .:/backend
    depends_on:
      - postgres
    # configuracion para activar la consola interactiva al contenedor
    stdin_open: true
    tty: true
  frontend:
    # vincular la carpeta del backend
    build: ./frontend
    # conectarse con el puerto 5173:de vite y 3001 para exponer al host
    ports:
      - '3001:5173'
    # vincular la carpeta del backend
    volumes:
      - ./frontend:/src
    # configuracion para activar la consola interactiva al contenedor
    stdin_open: true
    tty: true
    depends_on:
      - backend